### ISSUE TITLE
ReadTheDocs build failing on master

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#393]
RTD builds are failing with:

```
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/airr-standards/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/airr-standards/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/airr-standards/checkouts/latest/docs/conf.py", line 347, in <module>
    airr_name = airr_properties[airr_property]["x-airr"]["name"]
KeyError: 'name'
```

Seems to be due to replacing `x-airr: name` with `title`.

**Comment by javh** [comment]
Simple fix didn't work, so I started work on this and #390 in the `docs-tables`  branch. Give me a few days.

**Comment by franasa** [comment]
I'm sorry @javh , It was on me to do that fix but I was pushing it till `name` was removed. The MiAIRR table is rendering now and your lines look much better. Let me know if I can still help somehow.

**Comment by javh** [comment]
@franasa, no worries. I'm still working on it, but I think I know what needs to be done. My goal is to merge the three bits of table generation code into a single version based off yours (which is why I moved it around a bit).  I'll definitely ask you to review it once I'm done.
