### ISSUE TITLE
Update versioneer for python 3.12

### ISSUE THREAD

**Issue by ssnn-airr** [airr-community/airr-standards#742]
With python 3.12.1, `pip3 install airr` returns:  `AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?`. SafeConfigParser was deprecated in Python 3.2 and removed in 3.12.

The full message:

```
pip3 install airr
Collecting airr
  Downloading airr-1.5.0.tar.gz (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.4/64.4 kB 694.9 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /tmp/pip-install-80vk_za7/airr_ee7beefdf494462cb35a1cac5bd04014/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-80vk_za7/airr_ee7beefdf494462cb35a1cac5bd04014/setup.py", line 21, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-80vk_za7/airr_ee7beefdf494462cb35a1cac5bd04014/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-80vk_za7/airr_ee7beefdf494462cb35a1cac5bd04014/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-80vk_za7/airr_ee7beefdf494462cb35a1cac5bd04014/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by ssnn-airr** [comment]
Pull request#744

**Comment by schristley** [comment]
#744 has been merged
