### ISSUE TITLE
python error when using airr.read_rearrangement with gzip file

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#787]
When using `airr.read_rearrangement` on a gzip file, get this error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/airr/io.py", line 89, in __next__
    row = next(self.dict_reader)
  File "/usr/lib/python3.8/csv.py", line 110, in __next__
    self.fieldnames
  File "/usr/lib/python3.8/csv.py", line 97, in fieldnames
    self._fieldnames = next(self.reader)
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)
```

it seems we don't have a python test for this.

**Comment by schristley** [comment]
open with `'rt'` seems to work.
